version: '3'
 
services:
  desktop-base:
    build: .
    image: desktopcontainers/base-debian
    restart: always
    environment:
      SERVER_NAME: localhost

      VNC_SCREEN_DEPTH: 24

      #ENABLE_SUDO: enable
      #ENABLE_KIOSK: enable
    volumes:
      - ./certs:/certs
    ports:
      - "2222:22"
      - "8080:80"
      - "4443:443"
      #- "5900:5900"
